### ISSUE TITLE
Export location as address (instead of location name)

### ISSUE THREAD

**Issue by iroQuai** [reinzor/timeline-exporter#13]
Locations that have a business registered (or something like that) are shown in the export list with that name instead of the address. Is it possible to change this? It would save me heaps of post-processing (I visit around 30 places a month for work which I have to have fill in on an expenses sheet monthly.)

Hopefully someone can help with this!

**Comment by reinzor** [comment]
I am not sure what you mean, could you give an example; the `address` should be exported as a second column

**Comment by iroQuai** [comment]
So here's a screenshot to clarify my request some more. These are the first two columns, fromName and toName (and a part of the 3rd, duration)
 ![screenshot](https://user-images.githubusercontent.com/7004624/193918889-3cd9fedb-8e23-4dd9-862d-7cfcda640aa3.jpg)

I've removed privacy sensitive info, but I'll explain what is seen. 
- Red is my work location (which is called "werk" in my Google maps) and has the correct adres shown behind the name. (Street + house number. No city name though)
- orange and blue are addresses that don't have any personal or global name connected to it at Google. So it shows only the streetname + housenumber (again, no city name)
- in between was a stop at a supermarket, which Google recognised as ALDI supermarket from their public database. It doesn't show address, only the general shop name. 

For me, it would be best if all locations where formatted like  "{streetname} {housenumber}, {city}". i was hoping that that could be an option in settings?

**Comment by reinzor** [comment]
Now I understand it is for the mileage tab; will look into it.

**Comment by iroQuai** [comment]
A sorry forgot to mention that. Looks like a quick fix! TNX.
