### ISSUE TITLE
endTime format incorrect in csv export if export dates in local timezone is on

### ISSUE THREAD

**Issue by ToddDTaft** [reinzor/timeline-exporter#14]
If I have the "Export dates in local timezone" option turned on and export to a CSV file, the format of the timeEnd field is incorrect.  It's missing the date.

All of the below entries are from the timeEnd field of the file I export for activity today with this option turned on.  Note that the date is missing, as is the "T" character that separates the date and time in the timeBegin field.
2022-08-17:51:10.022
2022-08-18:09:49.000
2022-08-18:17:38.000
2022-08-18:26:41.000
2022-08-18:30:49.740

**Comment by effgee** [comment]
I noticed the same thing; the "DD" part of the date is missing, along with the "T"

**Comment by reinzor** [comment]
Fixed by https://github.com/reinzor/timeline-exporter/commit/2655c2b3ee07378039f1691042d67c461c32587b

**Comment by reinzor** [comment]
Thanks @effgee , @ToddDTaft , solved in next release
