### ISSUE TITLE
'from' date in filename of downloaded csv is wrong

### ISSUE THREAD

**Issue by effgee** [reinzor/timeline-exporter#16]
for example, if you download a range from 21Aug22 to 2Oct22, the filename is 2022-03-10_2022-02-10.csv

Its as though the 'from' date is calculated as the 'to' date plus 1, regardless of the actual 'from' date

**Comment by reinzor** [comment]
Thanks @effgee , will be solved in next release

**Comment by effgee** [comment]
Thanks again for providing such a great tool
