### ISSUE TITLE
Modify the app to make it work with the Google Takeout feature

### ISSUE THREAD

**Issue by alber70g** [reinzor/timeline-exporter#21]
Previously this all worked based on google timeline. Since timeline stopped working, you can now use Google Takeout. 
You can even make a scheduled takeout for timeline.

<img width="741" alt="image" src="https://github.com/user-attachments/assets/744cdef0-29cf-44dc-b94a-460ed59176c3">

**Comment by reinzor** [comment]
Same as previous issue: https://github.com/reinzor/timeline-exporter/issues/3

This will not be addressed: out of scope for this extension.
